### ISSUE TITLE
Unclear how non-recoverable Errors should be handled

### ISSUE THREAD

**Issue by AndrejMitrovic** [andrewlalis/handy-httpd#19]
Hi,

Consider a request handler that throws an error, say `AssertError`:

```D
import handy_httpd;
import std.stdio;

void main() {
    auto conf = ServerConfig.defaultValues;
    conf.port = 1108;
    conf.workerPoolSize = 2;  // only 2 active threads

    new HttpServer((ref ctx) {
            writefln("Handling: %s", ctx);
            int x;
            assert(x);  // AssertError (not HLT)
    }, conf).start();
}
```

Sending a request via curl will hang the client until it times out. Meanwhile the active worker thread will exit.

Since there were 2 active worker threads we'll be able to handle one more request and then that thread will exit too.
Subsequent requests will not be handled because there's no more active worker threads.

For a thrown `Exception` it makes sense to handle them. But how are we supposed to handle unrecoverable `Error`'s?

I'm thinking about some options:
- The threads should be spawned linked and if any child threads unexpectedly exit this should initiate shutdown in the parent thread.
- Alternatively Errors should be caught in the worker threads and immediately converted to a HALT instruction, forcing the entire app to shut down (without cleanup).
- Document that user-code request handlers must handle Errors themselves and make the choice of halting or exiting cleanly.

Maybe the last option is the easiest?

-----

Btw, really liking this library! It's way nicer to work with than vibe.d. Nice work @andrewlalis!

**Comment by AndrejMitrovic** [comment]
In case the client code catches the Errors and wants to both return 500 to the client and also stop the server, how would this be done?

We'd need to call `server.stop()`, but only after the request handler returns.

**Comment by AndrejMitrovic** [comment]
This seems to work for me:

```D
override void handle(ref HttpRequestContext ctx) {
    try {
        this.handleImpl(ctx);
    } catch (Error error) {
        this.server.stop();
        throw new Exception(format("Unhandled error: %s", error.msg));
    }
}
```

I've subclassed `HttpRequestHandler` which contains a `Server` instance, and implemented `handle()` which catches Errors and forces the server to stop. Additionally throwing an Exception here causes the server to return 500 to the client.

But I'm not entirely sure it's safe to return responses after `stop()` has been called.

**Comment by andrewlalis** [comment]
Hey, sorry for the late response, currently moving to a different continent... But you bring up a good point regarding handling of errors.

Only thing is, we are heavily discouraged from catching Error or its subtypes, since pretty much everything is undefined from that point onwards. So I do like your third idea the best, as it's pretty much what already happens, and since D is still very much in development, it would be pretty annoying if the server completely died each time an error happened.

Ideally, the server would respawn the dead thread so your server doesn't freeze up.

And yeah, as you noticed, even if you stop the server, any active socket stays open until the worker is done with it, so you can indeed safely write a 500 response and then shut down, or even do that in reverse order.

**Comment by AndrejMitrovic** [comment]
> Hey, sorry for the late response, currently moving to a different continent...

No worries, we're probably in different timezones anyway. Good luck with the move!

> And yeah, as you noticed, even if you stop the server, any active socket stays open until the worker is done with it, so you can indeed safely write a 500 response and then shut down, or even do that in reverse order.

That's good to hear.

And yeah, it probably shouldn't be the responsibility of the library to handle Errors, but user-code instead. That all sounds good to me.

**Comment by andrewlalis** [comment]
Closing this issue, because I'm releasing version `7.3.0` which introduces a managed thread pool with a "manager" thread that watches for workers that have died, and spawns new ones as needed. This should solve the issue that some people may have in the short-term with a worker dying due to an error. When resurrecting though, the manager will spit out a warning about that the worker died probably due to an uncaught error or exception, so I'm still encouraging people to be responsible with their errors.
