### ISSUE TITLE
Accept delegates in handlers

### ISSUE THREAD

**Issue by Castux** [andrewlalis/handy-httpd#43]
By changing https://github.com/andrewlalis/handy-httpd/blob/7eeab00edc207d8099127915d2ce788c8945e632/source/handy_httpd/components/handler.d#L65 to:

`alias HttpRequestHandlerFunction = void delegate(ref HttpRequestContext);`

This would allow more flexible handlers, like for instance mapping multiple routes to different member functions of a single object, or using closures over local variables.

Unless there is a good reason why that shouldn't happen, of course :)

**Comment by Castux** [comment]
FYI, I'm using this wrapper to be able to use delegates, inspired by the one in the source:

```
HttpRequestHandler toHandler(void delegate(ref HttpRequestContext ctx) fun)
{
	class Handler: HttpRequestHandler
	{
		void handle(ref HttpRequestContext ctx)
		{
			fun(ctx);
		}
	}

	return new Handler();
}
```

**Comment by andrewlalis** [comment]
Instead, I added the following compile-time function:
```d
/**
 * Compile-time function used to determine if something is a request handler
 * function. That is, it returns `void`, takes `ref HttpRequestContext` as a
 * single argument, and is callable.
 * Returns: True if the given type is a request handler function.
 */
bool isHttpRequestHandlerFunction(T)() {
    import std.traits;
    static if (isCallable!T && arity!T == 1) {
        import std.stdio;
        alias p = Parameters!T[0];
        alias s = ParameterStorageClassTuple!T[0];
        return (
            s == ParameterStorageClass.ref_
            && is(p == HttpRequestContext)
            && is(ReturnType!T == void)
        );
    } else {
        return false;
    }
}
```
Then, `toHandler` works with both functions and delegates, and should pretty much work with anything callable that takes `ref HttpRequestHandler` and returns `void`. With some updates to the other components, it's able to work with minimal changes in any code that uses this library.

The only breaking change is that you can no longer provide a function using lambda syntax like `(ref ctx) { ... }`, since it's not possible anymore for D to assume the type exactly. (I don't know if there's a way around that.)

**Comment by Castux** [comment]
Oh, really nice! Thanks for the quick reaction!
